export const CARTSELECTEDLIST = "CARTSELECTEDLIST";
export const REMOVECARTSELECTEDLIST = "REMOVECARTSELECTEDLIST";
export const SETPRIZE = "SETPRIZE";
export const CHECKOUTSELECTEDLIST = "CHECKOUTSELECTEDLIST";
export const BOOKCARTDATA = "BOOKCARTDATA";



